"""empty message

Revision ID: 0e00d1e14f46
Revises: adb67757f288
Create Date: 2018-05-13 12:08:36.704806

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0e00d1e14f46'
down_revision = 'adb67757f288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s_user', sa.Column('email', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s_user', 'email')
    # ### end Alembic commands ###
