"""empty message

Revision ID: 8667e9012d22
Revises: 8e93b3d900d5
Create Date: 2018-06-02 23:27:22.111182

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8667e9012d22'
down_revision = '8e93b3d900d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s_user', sa.Column('email_stat', sa.Integer(), nullable=True))
    op.add_column('s_user', sa.Column('phone_stat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s_user', 'phone_stat')
    op.drop_column('s_user', 'email_stat')
    # ### end Alembic commands ###
