"""empty message

Revision ID: 9ac355cdf49b
Revises: 
Create Date: 2018-05-12 17:34:10.226983

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9ac355cdf49b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ROLES = (
        ("NORMAL", "普通用户"),
        ("ADMIN", "管理员")
    )
    op.create_table('s_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('roles', sqlalchemy_utils.types.choice.ChoiceType(ROLES), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('like', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s_user')
    # ### end Alembic commands ###
