"""empty message

Revision ID: a6e969fe081d
Revises: 8be78b72e941
Create Date: 2018-05-26 16:33:33.460889

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a6e969fe081d'
down_revision = '8be78b72e941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('show_name', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('folder_group_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('is_trash', sa.INTEGER(), nullable=True),
    sa.Column('is_share', sa.INTEGER(), nullable=True),
    sa.Column('is_user_group', sa.INTEGER(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('f_folder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('folder_name', sa.String(length=500), nullable=True),
    sa.Column('folder_path', sa.String(length=1000), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('is_trash', sa.INTEGER(), nullable=True),
    sa.Column('is_share', sa.INTEGER(), nullable=True),
    sa.Column('is_user_group', sa.INTEGER(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('s_user', sa.Column('max_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s_user', 'max_size')
    op.drop_table('f_folder')
    op.drop_table('f_file')
    # ### end Alembic commands ###
