"""empty message

Revision ID: e6af78c67c28
Revises: 9ac355cdf49b
Create Date: 2018-05-12 17:37:31.439155

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6af78c67c28'
down_revision = '9ac355cdf49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s_user', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s_user', sa.Column('like', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
