"""empty message

Revision ID: f109ce4161dd
Revises: a6e969fe081d
Create Date: 2018-05-28 22:36:42.702463

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f109ce4161dd'
down_revision = 'a6e969fe081d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_ship')
    op.drop_table('f_task')
    op.add_column('f_file', sa.Column('group_id', sa.INTEGER(), nullable=True))
    op.add_column('f_file', sa.Column('group_path', sa.String(length=1000), nullable=True))
    op.drop_column('f_file', 'folder_group_id')
    op.drop_column('f_file', 'file_path')
    op.add_column('s_user', sa.Column('use_folder', sa.String(length=500), nullable=True))
    op.add_column('s_user', sa.Column('use_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s_user', 'use_size')
    op.drop_column('s_user', 'use_folder')
    op.add_column('f_file', sa.Column('file_path', mysql.VARCHAR(length=1000), nullable=True))
    op.add_column('f_file', sa.Column('folder_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('f_file', 'group_path')
    op.drop_column('f_file', 'group_id')
    op.create_table('f_task',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('task_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('task_title', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('task_key', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_run', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('run_interval', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('task_ship',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('task_info_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
